export const fr = {
  nav: {
    home: 'Accueil',
    about: 'À propos',
    rooms: 'Chambres',
    gallery: 'Galerie',
    contact: 'Contact',
    bookNow: 'Réserver',
  },
  hero: {
    subtitle: 'Offrez-vous un séjour hôtelier luxueux alliant confort et élégance, avec des équipements d haute qualité, un design raffiné et un service personnalisé exceptionnel.',
    viewRooms: 'VOIR NOS CHAMBRES',
    titleMain: 'ORA Lake View',
    titleSub: 'Séjour Panoramique dans les Alpes Suisses & Lac de Brienz',
    tagline: 'Un coin de paradis suisse conçu pour les rêveurs, les romantiques et les aventuriers.',
    facilitiesTitle: "Équipements de l'Hôtel",
    facilities: [
      { id: 'lobby', title: 'Lobby & Salon', desc: 'Salon chaleureux avec cheminée et hospitalité alpine', image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80' },
      { id: 'rooms', title: 'Chambres de Luxe', desc: 'Vues panoramiques sur le lac et confort absolu', image: 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=800&q=80' },
      { id: 'terrace', title: 'Terrasse Alpine', desc: 'Superbe terrasse panoramique surplombant le lac de Brienz', image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80' },
      { id: 'dining', title: 'Restaurant Panoramic', desc: 'Gastronomie suisse authentique et internationale', image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80' },
    ]
  },
  about: {
    badge: 'Qui Sommes-Nous',
    title: 'La Magie de Brienz au Meilleur Hôtel Vue Lac',
    description: 'Situé sur les rives émeraude du lac de Brienz, entouré par les sommets majestueux des Alpes bernoises, l’hôtel ORA Lake View offre une escapade suisse inoubliable. Réveillez-vous face au lac serein et accédez rapidement à Interlaken, Grindelwald et Lauterbrunnen.',
    storyTitle: 'Notre Héritage Alpin',
    storyText: 'Conçu avec l’élégance suisse et le luxe contemporain, notre hôtel associe le charme authentique des montagnes à la sophistication moderne.',
    features: [
      { title: 'Emplacement Privilégié', desc: 'Vue directe sur les eaux turquoise du lac de Brienz' },
      { title: 'À Deux Pas de la Gare', desc: 'Courte marche jusqu’à la gare de Brienz et au débarcadère' },
      { title: 'Parking Privé Gratuit', desc: 'Stationnement facile avec bornes de recharge électrique' },
      { title: 'Animaux Bienvenus', desc: 'Vos compagnons à quatre pattes sont accueillis avec joie' },
    ]
  },
  rooms: {
    title: 'Nos Chambres & Suites d’Exception',
    subtitle: 'Chaque chambre est aménagée avec soin pour offrir un confort maximal et une vue imprenable sur le lac de Brienz.',
    bookBtn: 'Réserver cette chambre',
    viewDetails: 'Détails de la chambre',
    specs: {
      size: 'Superficie',
      occupancy: 'Capacité',
      bed: 'Type de lit',
      view: 'Vue',
    },
    items: [
      {
        id: 'classic-lakeview',
        name: 'Chambre Classique Vue Lac',
        size: '22 m²',
        guests: '2 Adultes',
        bed: '1 Grand lit double',
        view: 'Lac de Brienz & Alpes',
        price: 'CHF 220 / nuit',
        image: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80',
        desc: 'Chambre élégante et douillette avec balcon privé donnant sur le lac étincelant.',
        amenities: ['Wi-Fi Gratuit', 'Balcon Privé', 'Smart TV', 'Douche Pluie', 'Machine Espresso'],
      },
      {
        id: 'lakeview-studio',
        name: 'Studio Vue Lac',
        size: '22 m²',
        guests: '2 Adultes',
        bed: '1 Lit King-size',
        view: 'Vue Panoramique Lac',
        price: 'CHF 250 / nuit',
        image: 'https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=800&q=80',
        desc: 'Studio moderne à plan ouvert avec finitions haut de gamme et grandes baies vitrées.',
        amenities: ['Wi-Fi Gratuit', 'Coin Salon', 'Mini Réfrigérateur', 'Douche Pluie', 'Bureau de travail'],
      },
      {
        id: 'lakeview-trio',
        name: 'Chambre Trio Vue Lac',
        size: '28 m²',
        guests: '3 Personnes',
        bed: '1 Lit King + 1 Lit Simple',
        view: 'Vue Lac & Montagne',
        price: 'CHF 310 / nuit',
        image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80',
        desc: 'Idéale pour les petites familles avec espace généreux et grand balcon panoramique.',
        amenities: ['Wi-Fi Gratuit', 'Grand Balcon', 'Grande Salle de Bain', 'Cafetière', 'Coffre-fort'],
      },
      {
        id: 'majestic-king',
        name: 'Suite Majestic King Vue Lac',
        size: '32 m²',
        guests: '2 Adultes',
        bed: '1 Lit Super King',
        view: 'Vue Panoramique 180° Lac',
        price: 'CHF 380 / nuit',
        image: 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=800&q=80',
        desc: 'Expérience de luxe ultime avec immense terrasse privée et baignoire îlot.',
        amenities: ['Terrasse Privée', 'Baignoire Îlot', 'Minibar Premium', 'Produits de Soin', 'Nespresso'],
      },
      {
        id: 'queens-vista',
        name: 'Suite Queens Vista',
        size: '40 m²',
        guests: '4 Personnes',
        bed: '1 Lit King + Canapé-lit',
        view: 'Alpes & Lac de Brienz',
        price: 'CHF 460 / nuit',
        image: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=800&q=80',
        desc: 'Suite prestigieuse avec baie vitrée toute hauteur, espace repas et chambre principale.',
        amenities: ['Espace Salon', 'Table à manger', 'Baies Vitrées', 'Double Vasque', 'Dressing'],
      },
      {
        id: 'alpine-retreat',
        name: 'Suite Familiale Alpine',
        size: '50 m²',
        guests: '5 Personnes',
        bed: '2 Lits King + Méridienne',
        view: 'Double Balcon Lac & Montagne',
        price: 'CHF 540 / nuit',
        image: 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop&w=800&q=80',
        desc: 'Grande suite de 2 chambres conçue pour des vacances en famille inoubliables.',
        amenities: ['2 Chambres', 'Deux Balcons', 'Coin Cuisine', 'Espace Repas', '2 Salles de Bain'],
      },
    ]
  },
  gallery: {
    title: 'Voyage Visuel au Coeur de l’ORA Lake View',
    subtitle: 'Laissez-vous séduire par les paysages grandioses, le design raffiné et l’ambiance paisible de notre hôtel.',
    categories: {
      all: 'Toutes les photos',
      rooms: 'Chambres & Suites',
      view: 'Vues Panoramiques',
      dining: 'Restaurant & Bar',
      facilities: 'Équipements',
    }
  },
  contact: {
    title: 'Contactez-Nous',
    subtitle: 'Nous sommes à votre entière disposition pour vos demandes de renseignements et de réservations.',
    addressTitle: 'Adresse',
    addressValue: 'Hauptstrasse 32, 3853 Niederried bei Interlaken, Suisse',
    phoneTitle: 'Téléphone',
    phoneValue: '+41 77 973 19 81',
    emailTitle: 'E-mail',
    emailValue: 'info@oralakeview.com',
    hoursTitle: 'Horaires Réception',
    hoursValue: '07h30 - 22h00 tous les jours',
    form: {
      name: 'Nom Complet',
      email: 'Adresse E-mail',
      subject: 'Sujet',
      message: 'Message / Demandes Particulières',
      submit: 'Envoyer le Message',
      success: 'Merci ! Votre message a été envoyé avec succès.',
    }
  },
  footer: {
    brandText: 'ORA Lake View Hotel & Restaurant - Votre havre de paix au cœur des Alpes suisses au bord du lac de Brienz.',
    quickLinks: 'Liens Rapides',
    roomTypes: 'Chambres',
    contactUs: 'Contact',
    copyright: '© 2026 ORA Lake View Hotel. Tous droits réservés.',
  }
};
