export const it = {
  nav: {
    home: 'Home',
    about: 'Chi Siamo',
    rooms: 'Camere',
    gallery: 'Galleria',
    contact: 'Contatti',
    bookNow: 'Prenota Ora',
  },
  hero: {
    subtitle: 'Concediti un soggiorno di lusso in un hotel dove il comfort incontra lo stile, offrendo servizi di primissimo ordine, design elegante e un servizio personalizzato eccezionale.',
    viewRooms: 'SCOPRI LE CAMERE',
    titleMain: 'ORA Lake View',
    titleSub: 'Soggiorno Panoramico tra le Alpi Svizzere e il Lago di Brienz',
    tagline: 'Un angolo di paradiso svizzero per sognatori, romantici e amanti dell avventura.',
    facilitiesTitle: 'Servizi dell Hotel',
    facilities: [
      { id: 'lobby', title: 'Lobby & Lounge', desc: 'Accogliente salone con camino e ospitalità alpina', image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80' },
      { id: 'rooms', title: 'Camere di Lusso', desc: 'Viste panoramiche sul lago e massimo comfort', image: 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=800&q=80' },
      { id: 'terrace', title: 'Terrazza Alpina', desc: 'Spettacolare terrazza ristorante sul Lago di Brienz', image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80' },
      { id: 'dining', title: 'Ristorante Vista Lago', desc: 'Gastronomia svizzera autentica e internazionale', image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80' },
    ]
  },
  about: {
    badge: 'Chi Siamo',
    title: 'La Magia di Brienz nel Miglior Hotel Vista Lago',
    description: 'Situato sulle sponde smeraldo del Lago di Brienz e circondato dalle maestose Alpi Bernesi, l’ORA Lake View Hotel offre una vacanza svizzera indimenticabile. Svegliati con riflessi d’acqua incantevoli e raggiungi facilmente Interlaken, Grindelwald e Lauterbrunnen.',
    storyTitle: 'La Nostra Tradizione Alpina',
    storyText: 'Realizzato con eleganza svizzera e lusso contemporaneo, il nostro hotel fonde il fascino autentico della montagna con una raffinata modernità.',
    features: [
      { title: 'Posizione Esclusiva', desc: 'Vista diretta sulle acque turchesi del Lago di Brienz' },
      { title: 'A Due Passi dalla Stazione', desc: 'Breve passeggiata per la stazione di Brienz e i moli' },
      { title: 'Parcheggio Privato Gratuito', desc: 'Parcheggio comodo con stazioni di ricarica EV' },
      { title: 'Pet-Friendly', desc: 'Accogliamo i tuoi amici a quattro zampe a braccia aperte' },
    ]
  },
  rooms: {
    title: 'Le Nostre Camere e Suite di Lusso',
    subtitle: 'Ogni camera è studiata nei dettagli per garantire massimo comfort e viste mozzafiato sul Lago di Brienz e sulle Alpi.',
    bookBtn: 'Prenota Questa Camera',
    viewDetails: 'Dettagli Camera',
    specs: {
      size: 'Superficie',
      occupancy: 'Ospiti',
      bed: 'Tipo di letto',
      view: 'Vista',
    },
    items: [
      {
        id: 'classic-lakeview',
        name: 'Camera Classica Vista Lago',
        size: '22 m²',
        guests: '2 Adulti',
        bed: '1 Letto Matrimoniale',
        view: 'Lago di Brienz e Alpi',
        price: 'CHF 220 / notte',
        image: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80',
        desc: 'Camera elegante e accogliente con balcone privato affacciato sulle acque scintillanti del lago.',
        amenities: ['Wi-Fi Gratuito', 'Balcone Privato', 'Smart TV', 'Doccia a Pioggia', 'Macchina Espresso'],
      },
      {
        id: 'lakeview-studio',
        name: 'Studio Vista Lago',
        size: '22 m²',
        guests: '2 Adulti',
        bed: '1 Letto King',
        view: 'Vista Panoramica Lago',
        price: 'CHF 250 / notte',
        image: 'https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=800&q=80',
        desc: 'Studio moderno open-space con finiture di design e ampie vetrate sul lago.',
        amenities: ['Wi-Fi Gratuito', 'Angolo Salotto', 'Mini Frigo', 'Doccia a Pioggia', 'Scrittoio'],
      },
      {
        id: 'lakeview-trio',
        name: 'Camera Trio Vista Lago',
        size: '28 m²',
        guests: '3 Ospiti',
        bed: '1 King + 1 Singolo',
        view: 'Panorama Lago e Montagna',
        price: 'CHF 310 / notte',
        image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80',
        desc: 'Ideale per piccole famiglie o gruppi con spazi generosi e ampio balcone panoramico.',
        amenities: ['Wi-Fi Gratuito', 'Ampio Balcone', 'Bagno Spazioso', 'Macchina Caffè', 'Cassaforte'],
      },
      {
        id: 'majestic-king',
        name: 'Suite Majestic King Vista Lago',
        size: '32 m²',
        guests: '2 Adulti',
        bed: '1 Letto Super King',
        view: 'Vista Frontale 180° sul Lago',
        price: 'CHF 380 / notte',
        image: 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=800&q=80',
        desc: 'Vivi il massimo del lusso con una vasta terrazza solarium e vasca da bagno freestanding.',
        amenities: ['Terrazza Privata', 'Vasca da Bagno', 'Minibar Premium', 'Set di Cortesia', 'Nespresso'],
      },
      {
        id: 'queens-vista',
        name: 'Suite Queens Vista',
        size: '40 m²',
        guests: '4 Ospiti',
        bed: '1 Letto King + Divano Letto',
        view: 'Alpi e Lago di Brienz',
        price: 'CHF 460 / notte',
        image: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=800&q=80',
        desc: 'Suite di prestigio con vetrate a tutta altezza, zona pranzo e camera padronale.',
        amenities: ['Zona Salotto', 'Tavolo da Pranzo', 'Vetrate Panoramiche', 'Doppio Lavabo', 'Cabina Armadio'],
      },
      {
        id: 'alpine-retreat',
        name: 'Suite Familiare Alpina',
        size: '50 m²',
        guests: '5 Ospiti',
        bed: '2 Letti King + Daybed',
        view: 'Doppio Balcone Lago e Monti',
        price: 'CHF 540 / notte',
        image: 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop&w=800&q=80',
        desc: 'Ampia suite con 2 camere da letto pensata per vacanze in famiglia indimenticabili sulle Alpi.',
        amenities: ['2 Camere da letto', 'Due Balconi', 'Angolo Cottura', 'Pranzo in Famiglia', '2 Bagni'],
      },
    ]
  },
  gallery: {
    title: 'Viaggio Visivo all ORA Lake View',
    subtitle: 'Immergiti negli splendidi paesaggi, negli interni di classe e nell atmosfera serena del nostro hotel.',
    categories: {
      all: 'Tutte le Foto',
      rooms: 'Camere e Suite',
      view: 'Viste Panoramiche',
      dining: 'Ristorante e Bar',
      facilities: 'Servizi',
    }
  },
  contact: {
    title: 'Mettiti in Contatto con Noi',
    subtitle: 'Siamo felici di assisterti per informazioni, prenotazioni di camere e richieste speciali.',
    addressTitle: 'Indirizzo',
    addressValue: 'Hauptstrasse 32, 3853 Niederried bei Interlaken, Svizzera',
    phoneTitle: 'Telefono',
    phoneValue: '+41 77 973 19 81',
    emailTitle: 'E-mail',
    emailValue: 'info@oralakeview.com',
    hoursTitle: 'Orari Reception',
    hoursValue: '07:30 - 22:00 tutti i giorni',
    form: {
      name: 'Nome Completo',
      email: 'Indirizzo E-mail',
      subject: 'Oggetto',
      message: 'Messaggio / Richieste Speciali',
      submit: 'Invia Messaggio',
      success: 'Grazie! Il tuo messaggio è stato inviato con successo.',
    }
  },
  footer: {
    brandText: 'ORA Lake View Hotel & Restaurant - Il tuo rifugio sereno sulle Alpi Svizzere al Lago di Brienz.',
    quickLinks: 'Link Rapidi',
    roomTypes: 'Tipologie Camere',
    contactUs: 'Contatti',
    copyright: '© 2026 ORA Lake View Hotel. Tutti i diritti riservati.',
  }
};
