export const en = {
  nav: {
    home: 'Home',
    about: 'About Us',
    rooms: 'Rooms',
    gallery: 'Gallery',
    contact: 'Contact Us',
    bookNow: 'Book Now',
  },
  hero: {
    subtitle: 'A slice of Swiss heaven crafted for dreamers, romantics, and adventure seekers alike.',
    viewRooms: 'VIEW OUR ROOMS',
    titleMain: 'ORA Lake View',
    titleSub: 'Scenic Swiss Alps & Lake View Stay',
    tagline: 'A slice of Swiss heaven crafted for dreamers, romantics, and adventure seekers alike.',
    facilitiesTitle: "Hotel's Facilities",
    facilities: [
      { id: 'lobby', title: 'Guest Lobby', desc: 'Warm fireside lounge with alpine hospitality', image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80' },
      { id: 'rooms', title: 'Luxury Rooms', desc: 'Panoramic lakefront vistas & premium comfort', image: 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=800&q=80' },
      { id: 'terrace', title: 'Alpine Terrace', desc: 'Breathtaking dining deck over Lake Brienz', image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80' },
      { id: 'dining', title: 'Lakeview Restaurant', desc: 'Authentic Swiss & international gastronomy', image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80' },
      { id: 'parking', title: 'Free EV Parking', desc: 'Complimentary private parking with EV chargers', image: 'https://images.unsplash.com/photo-1506521782023-6058fda68c83?auto=format&fit=crop&w=800&q=80' },
      { id: 'pets', title: 'Pet Friendly', desc: 'Welcoming four-legged companions warmly', image: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=800&q=80' },
    ]
  },
  welcome: {
    subTitle: 'WELCOME TO ORA LAKEVIEW HOTEL',
    title: 'Where Alpine Serenity Meets Waterfront Luxury',
    text1: 'When crisp alpine air refreshes the soul and shimmering turquoise waters invite you to slow down, ORA Lake View welcomes you to a place where Swiss warmth, style, and peace converge in the heart of Brienz.',
    text2: 'Perfectly situated on the emerald shores of Lake Brienz surrounded by the majestic Bernese Alps, our hotel is your ideal sanctuary for scenic lakefront breaks, mountain adventures, and peaceful escapes. Just 3 minutes walk from Brienz train station and boat docks, everything you need is at your doorstep.',
    quote: '"If you are looking for an unforgettable Swiss getaway filled with breathtaking panoramas, luxury comfort, and heartfelt hospitality, you are in the right place. Let us craft a serene stay for you."',
    badgeText: '3 MINS WALK TO BRIENZ STATION & DOCKS',
    highlights: [
      { title: 'Prime Lakefront Location', desc: 'Direct 180° views of turquoise Lake Brienz & Bernese Alps' },
      { title: 'Free EV Parking & Charging', desc: 'Complimentary private parking with electric vehicle chargers' },
      { title: 'Pet-Friendly Alpine Hospitality', desc: 'Welcoming your four-legged companions with warmth and care' },
    ],
    ctaBtn: 'DISCOVER OUR ROOMS',
  },
  about: {
    badge: 'Who We Are',
    title: 'Whispers of Brienz at the Best Lakeview Hotel',
    description: 'Situated on the emerald shores of Lake Brienz surrounded by the majestic Bernese Alps, ORA Lake View Hotel offers an unforgettable Swiss retreat. Wake up to serene water reflections, breathe in crisp alpine air, and enjoy seamless access to world-renowned destinations like Interlaken, Grindelwald, and Lauterbrunnen.',
    storyTitle: 'Our Alpine Heritage',
    storyText: 'Crafted with Swiss elegance and contemporary luxury, our hotel combines authentic mountain charm with modern sophistication. Whether you are seeking a peaceful escape or outdoor adventures, ORA Lake View is your home in the heart of Switzerland.',
    features: [
      { title: 'Prime Lakefront', desc: 'Direct views of turquoise Lake Brienz and mountain peaks' },
      { title: 'Minutes to Transit', desc: 'Short walk to Brienz railway station and boat docks' },
      { title: 'Free Private Parking', desc: 'Hassle-free parking with EV charging stations' },
      { title: 'Pet-Friendly Stay', desc: 'Welcoming your four-legged companions with warmth' },
    ]
  },
  rooms: {
    title: 'Our Signature Accommodations',
    subtitle: 'Each room is thoughtfully designed to maximize comfort while offering breathtaking vistas of Lake Brienz and the Swiss Alps.',
    bookBtn: 'Book This Room',
    viewDetails: 'View Specifications',
    specs: {
      size: 'Size',
      occupancy: 'Guests',
      bed: 'Bed Type',
      view: 'View',
    },
    items: [
      {
        id: 'classic-lakeview',
        name: 'Classic Lakeview Room',
        size: '22 m²',
        guests: '2 Adults',
        bed: '1 Queen Bed',
        view: 'Lake Brienz & Mountain View',
        price: 'CHF 220 / night',
        image: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80',
        desc: 'Elegant & cozy room featuring a private balcony overlooking the shimmering waters of Lake Brienz.',
        amenities: ['Free Wi-Fi', 'Private Balcony', 'Smart TV', 'Rain Shower', 'Espresso Machine'],
      },
      {
        id: 'lakeview-studio',
        name: 'Lakeview Studio',
        size: '22 m²',
        guests: '2 Adults',
        bed: '1 King Bed',
        view: 'Panorama Lake View',
        price: 'CHF 250 / night',
        image: 'https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=800&q=80',
        desc: 'Modern open-plan studio equipped with high-end designer finishes and expansive lakefront windows.',
        amenities: ['Free Wi-Fi', 'Seating Corner', 'Mini Fridge', 'Rain Shower', 'Work Desk'],
      },
      {
        id: 'lakeview-trio',
        name: 'Lakeview Trio Room',
        size: '28 m²',
        guests: '3 Guests',
        bed: '1 King + 1 Single Bed',
        view: 'Full Lake & Alps Vista',
        price: 'CHF 310 / night',
        image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80',
        desc: 'Ideal for small families or friend groups, offering spacious bedding and a wide panorama deck.',
        amenities: ['Free Wi-Fi', 'Wide Balcony', 'Spacious Bath', 'Coffee Maker', 'Safe Box'],
      },
      {
        id: 'majestic-king',
        name: 'Majestic Lakeview King',
        size: '32 m²',
        guests: '2 Adults',
        bed: '1 Super King Bed',
        view: 'Unobstructed 180° Lakefront',
        price: 'CHF 380 / night',
        image: 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=800&q=80',
        desc: 'Experience pure luxury with an oversized terrace, plush super king bedding, and a deep soaking tub.',
        amenities: ['Private Sun Deck', 'Soaking Bathtub', 'Premium Minibar', 'Luxury Toiletries', 'Nespresso'],
      },
      {
        id: 'queens-vista',
        name: 'Queens Vista Suite',
        size: '40 m²',
        guests: '4 Guests',
        bed: '1 King Bed + Lounge Sofa',
        view: 'Panoramic Alps & Lake',
        price: 'CHF 460 / night',
        image: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=800&q=80',
        desc: 'Grand suite featuring floor-to-ceiling glass windows, dining area, and master bedroom suite.',
        amenities: ['Lounge Area', 'Dining Table', 'Panoramic Windows', 'Double Vanity', 'Walk-in Closet'],
      },
      {
        id: 'alpine-retreat',
        name: 'Alpine Family Retreat',
        size: '50 m²',
        guests: '5 Guests',
        bed: '2 King Beds + Daybed',
        view: 'Dual Lake & Mountain Deck',
        price: 'CHF 540 / night',
        image: 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop&w=800&q=80',
        desc: 'Spacious 2-bedroom suite designed for unforgettable family getaways in the heart of the Swiss Alps.',
        amenities: ['2 Bedrooms', 'Dual Balconies', 'Kitchenette', 'Family Dining', '2 Bathrooms'],
      },
    ]
  },
  gallery: {
    title: 'Visual Journey through ORA Lake View',
    subtitle: 'Immerse yourself in the stunning scenery, luxury interiors, and tranquil ambience of our hotel.',
    categories: {
      all: 'All Photos',
      rooms: 'Rooms & Suites',
      view: 'Scenic Views',
      dining: 'Restaurant & Bar',
      facilities: 'Facilities',
    }
  },
  contact: {
    title: 'Get In Touch With Us',
    subtitle: 'We are delighted to assist you with inquiries, room reservations, and special event requests.',
    addressTitle: 'Address',
    addressValue: 'Hauptstrasse 44, 3855 Brienz, Switzerland',
    phoneTitle: 'Phone',
    phoneValue: '+41 33 951 13 41',
    emailTitle: 'Email',
    emailValue: 'info@oralakeview.com',
    hoursTitle: 'Front Desk Hours',
    hoursValue: '07:30 - 22:00 daily',
    form: {
      name: 'Your Full Name',
      email: 'Email Address',
      subject: 'Subject',
      message: 'Message / Special Requests',
      submit: 'Send Message',
      success: 'Thank you! Your message has been sent successfully.',
    }
  },
  footer: {
    brandText: 'ORA Lake View Hotel & Restaurant - Your serene sanctuary in the Swiss Alps on Lake Brienz.',
    quickLinks: 'Quick Links',
    roomTypes: 'Room Types',
    contactUs: 'Contact Us',
    copyright: '© 2026 ORA Lake View Hotel. All rights reserved.',
  }
};
