export const en = {
  nav: {
    home: 'Home',
    about: 'About Us',
    rooms: 'Rooms',
    gallery: 'Gallery',
    contact: 'Contact Us',
    bookNow: 'Book Now',
  },
  hero: {
    subtitle: 'A slice of Swiss heaven crafted for dreamers, romantics, and adventure seekers alike.',
    viewRooms: 'VIEW OUR ROOMS',
    titleMain: 'ORA Lake View',
    titleSub: 'Scenic Swiss Alps & Lake View Stay',
    tagline: 'A slice of Swiss heaven crafted for dreamers, romantics, and adventure seekers alike.',
    facilitiesTitle: "Hotel's Facilities",
    facilities: [
      { id: 'lobby', title: 'Guest Lobby', desc: 'Warm fireside lounge with alpine hospitality', image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80' },
      { id: 'rooms', title: 'Luxury Rooms', desc: 'Panoramic lakefront vistas & premium comfort', image: 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=800&q=80' },
      { id: 'terrace', title: 'Alpine Terrace', desc: 'Breathtaking dining deck over Lake Brienz', image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80' },
      { id: 'dining', title: 'Lakeview Restaurant', desc: 'Authentic Swiss & international gastronomy', image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80' },
      { id: 'parking', title: 'Free EV Parking', desc: 'Complimentary private parking with EV chargers', image: 'https://images.unsplash.com/photo-1506521782023-6058fda68c83?auto=format&fit=crop&w=800&q=80' },
      { id: 'pets', title: 'Pet Friendly', desc: 'Welcoming four-legged companions warmly', image: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=800&q=80' },
    ]
  },
  welcome: {
    subTitle: 'WELCOME TO ORA LAKEVIEW HOTEL',
    title: 'Where Alpine Serenity Meets Waterfront Luxury',
    text1: 'Situated on the turquoise shores of Lake Brienz in Niederried bei Interlaken, ORA Lake View offers a tranquil Swiss sanctuary just 2 minutes walk from Niederried train station and 300 meters from the ferry dock, only 7 km from Interlaken.',
    quote: '"Experience an unforgettable Swiss getaway filled with breathtaking lake views, alpine air, and warm hospitality."',
    badgeText: '2 MINS WALK TO TRAIN STATION & FERRY DOCK',
    ctaBtn: 'DISCOVER OUR ROOMS',
  },
  about: {
    badge: 'Who We Are',
    title: 'Wake up to the soft shimmer of Lake Brienz, where every glance out your window reveals nature at its finest.',
    description: 'At ORA Lakeview Hotel, the breathtaking views of the Swiss Alps and pristine lake set the stage for unforgettable memories.',
    storyText: 'Perfectly located just 2 minutes from the train station, 1 minute from the bus stop, and 5 minutes from the ferry, we offer unmatched convenience to explore the wonders of the region. And with free parking and no extra fees, we’ve made sure your stay is as effortless as it is beautiful.',
    quote: 'And yes, we’re a pet-friendly hotel! Bring your four-legged friends along - they’ll love the view just as much as you do. Here, your story becomes our story.',
    features: [
      { title: 'Prime Lakefront Location', desc: 'Direct views of turquoise Lake Brienz & Bernese Alps' },
      { title: 'Minutes to Transit', desc: '2 mins to train station, 1 min to bus & 5 mins to ferry' },
      { title: 'Free Parking & No Extra Fees', desc: 'Hassle-free private parking with EV charging' },
      { title: 'Pet-Friendly Stay', desc: 'Welcoming your four-legged companions with warmth' },
    ]
  },
  rooms: {
    title: 'Our Signature Accommodations',
    subtitle: 'Each room is thoughtfully designed to maximize comfort while offering breathtaking vistas of Lake Brienz and the Swiss Alps.',
    bookBtn: 'Book This Room',
    viewDetails: 'View Specifications',
    specs: {
      size: 'Size',
      occupancy: 'Guests',
      bed: 'Bed Type',
      view: 'View',
    },
    items: [
      {
        id: 'classic-lakeview',
        name: 'Classic Lakeview Room',
        size: '22 m²',
        guests: '2 Adults',
        bed: '1 Queen Bed',
        view: 'Lake Brienz & Mountain View',
        price: 'CHF 220 / night',
        image: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80',
        desc: 'Elegant & cozy room featuring a private balcony overlooking the shimmering waters of Lake Brienz.',
        amenities: ['Free Wi-Fi', 'Private Balcony', 'Smart TV', 'Rain Shower', 'Espresso Machine'],
      },
      {
        id: 'lakeview-studio',
        name: 'Lakeview Studio',
        size: '22 m²',
        guests: '2 Adults',
        bed: '1 King Bed',
        view: 'Panorama Lake View',
        price: 'CHF 250 / night',
        image: 'https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=800&q=80',
        desc: 'Modern open-plan studio equipped with high-end designer finishes and expansive lakefront windows.',
        amenities: ['Free Wi-Fi', 'Seating Corner', 'Mini Fridge', 'Rain Shower', 'Work Desk'],
      },
      {
        id: 'lakeview-trio',
        name: 'Lakeview Trio Room',
        size: '28 m²',
        guests: '3 Guests',
        bed: '1 King + 1 Single Bed',
        view: 'Full Lake & Alps Vista',
        price: 'CHF 310 / night',
        image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80',
        desc: 'Ideal for small families or friend groups, offering spacious bedding and a wide panorama deck.',
        amenities: ['Free Wi-Fi', 'Wide Balcony', 'Spacious Bath', 'Coffee Maker', 'Safe Box'],
      },
      {
        id: 'majestic-king',
        name: 'Majestic Lakeview King',
        size: '32 m²',
        guests: '2 Adults',
        bed: '1 Super King Bed',
        view: 'Unobstructed 180° Lakefront',
        price: 'CHF 380 / night',
        image: 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=800&q=80',
        desc: 'Experience pure luxury with an oversized terrace, plush super king bedding, and a deep soaking tub.',
        amenities: ['Private Sun Deck', 'Soaking Bathtub', 'Premium Minibar', 'Luxury Toiletries', 'Nespresso'],
      },
      {
        id: 'queens-vista',
        name: 'Queens Vista Suite',
        size: '40 m²',
        guests: '4 Guests',
        bed: '1 King Bed + Lounge Sofa',
        view: 'Panoramic Alps & Lake',
        price: 'CHF 460 / night',
        image: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=800&q=80',
        desc: 'Grand suite featuring floor-to-ceiling glass windows, dining area, and master bedroom suite.',
        amenities: ['Lounge Area', 'Dining Table', 'Panoramic Windows', 'Double Vanity', 'Walk-in Closet'],
      },
      {
        id: 'alpine-retreat',
        name: 'Alpine Family Retreat',
        size: '50 m²',
        guests: '5 Guests',
        bed: '2 King Beds + Daybed',
        view: 'Dual Lake & Mountain Deck',
        price: 'CHF 540 / night',
        image: 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop&w=800&q=80',
        desc: 'Spacious 2-bedroom suite designed for unforgettable family getaways in the heart of the Swiss Alps.',
        amenities: ['2 Bedrooms', 'Dual Balconies', 'Kitchenette', 'Family Dining', '2 Bathrooms'],
      },
    ]
  },
  gallery: {
    title: 'Visual Journey through ORA Lake View',
    subtitle: 'Immerse yourself in the stunning scenery, luxury interiors, and tranquil ambience of our hotel.',
    categories: {
      all: 'All Photos',
      rooms: 'Rooms & Suites',
      view: 'Scenic Views',
      dining: 'Restaurant & Bar',
      facilities: 'Facilities',
    }
  },
  contact: {
    title: 'Get In Touch With Us',
    subtitle: 'We are delighted to assist you with inquiries, room reservations, and special event requests.',
    addressTitle: 'Address',
    addressValue: 'Hauptstrasse 32, 3853 Niederried bei Interlaken, Switzerland',
    phoneTitle: 'Phone',
    phoneValue: '+41 77 973 19 81',
    emailTitle: 'Email',
    emailValue: 'info@oralakeview.com',
    hoursTitle: 'Front Desk Hours',
    hoursValue: '07:30 - 22:00 daily',
    form: {
      name: 'Your Full Name',
      email: 'Email Address',
      subject: 'Subject',
      message: 'Message / Special Requests',
      submit: 'Send Message',
      success: 'Thank you! Your message has been sent successfully.',
    }
  },
  footer: {
    brandText: 'ORA Lake View Hotel & Restaurant - Your serene sanctuary in the Swiss Alps on Lake Brienz.',
    quickLinks: 'Quick Links',
    roomTypes: 'Room Types',
    contactUs: 'Contact Us',
    copyright: '© 2026 ORA Lake View Hotel. All rights reserved.',
  }
};
