export const de = {
  nav: {
    home: 'Startseite',
    about: 'Über uns',
    rooms: 'Zimmer',
    gallery: 'Galerie',
    contact: 'Kontakt',
    bookNow: 'Jetzt Buchen',
  },
  hero: {
    subtitle: 'Gönnen Sie sich einen luxuriösen Hotelaufenthalt, bei dem Komfort auf Stil trifft, mit erstklassigen Annehmlichkeiten, elegantem Design und erstklassigem Service.',
    viewRooms: 'ZIMMER ENTDECKEN',
    titleMain: 'ORA Lake View',
    titleSub: 'Malerischer Aufenthalt in den Schweizer Alpen & am Brienzersee',
    tagline: 'Ein Stück Schweizer Himmel für Träumer, Romantiker und Abenteurer.',
    facilitiesTitle: 'Hotelausstattung',
    facilities: [
      { id: 'lobby', title: 'Gästelobby', desc: 'Gemütliche Kaminlounge mit alpiner Gastfreundschaft', image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80' },
      { id: 'rooms', title: 'Luxuszimmer', desc: 'Panoramablick auf den See & höchster Komfort', image: 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=800&q=80' },
      { id: 'terrace', title: 'Alpine Terrasse', desc: 'Atemberaubendes Restaurantdeck über dem Brienzersee', image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80' },
      { id: 'dining', title: 'See-Restaurant', desc: 'Authentische Schweizer & internationale Gastronomie', image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80' },
    ]
  },
  about: {
    badge: 'Wer Wir Sind',
    title: 'Zauber von Brienz im besten Seehotel',
    description: 'Das ORA Lake View Hotel liegt am smaragdgrünen Ufer des Brienzersees, umgeben von den majestätischen Berner Alpen, und bietet ein unvergessliches Schweizer Erlebnis. Wachen Sie mit sanften Wasserreflexionen auf und erkunden Sie Interlaken, Grindelwald und Lauterbrunnen.',
    storyTitle: 'Unser Alpines Erbe',
    storyText: 'Mit Schweizer Eleganz und zeitgemäßem Luxus gestaltet, verbindet unser Hotel authentischen Bergcharme mit moderner Raffinesse.',
    features: [
      { title: 'Erstklassige Seelage', desc: 'Direkter Blick auf den türkisblauen Brienzersee und die Gipfel' },
      { title: 'Nahe am Bahnhof', desc: 'Wenige Gehminuten zum Bahnhof Brienz und Schiffsanleger' },
      { title: 'Kostenlose Parkplätze', desc: 'Bequeme Parkplätze mit E-Ladestationen' },
      { title: 'Haustierfreundlich', desc: 'Wir heißen Ihre vierbeinigen Begleiter herzlich willkommen' },
    ]
  },
  rooms: {
    title: 'Unsere Exklusiven Zimmer',
    subtitle: 'Jedes Zimmer ist durchdacht gestaltet, um maximalen Komfort und atemberaubende Aussichten auf den Brienzersee zu bieten.',
    bookBtn: 'Zimmer Buchen',
    viewDetails: 'Details Anzeigen',
    specs: {
      size: 'Größe',
      occupancy: 'Gäste',
      bed: 'Bettentyp',
      view: 'Aussicht',
    },
    items: [
      {
        id: 'classic-lakeview',
        name: 'Klassisches Seeblick-Zimmer',
        size: '22 m²',
        guests: '2 Erwachsene',
        bed: '1 Doppelbett',
        view: 'Brienzersee & Alpenpanorama',
        price: 'CHF 220 / Nacht',
        image: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80',
        desc: 'Elegantes & gemütliches Zimmer mit privatem Balkon mit Blick auf den schimmernden Brienzersee.',
        amenities: ['Kostenloses WLAN', 'Privater Balkon', 'Smart-TV', 'Regendusche', 'Espressomaschine'],
      },
      {
        id: 'lakeview-studio',
        name: 'Seeblick Studio',
        size: '22 m²',
        guests: '2 Erwachsene',
        bed: '1 King-Bett',
        view: 'Panorama-Seeblick',
        price: 'CHF 250 / Nacht',
        image: 'https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=800&q=80',
        desc: 'Modernes Studio mit hochwertigem Design und großen Panoramafenstern direkt am Seeufer.',
        amenities: ['Kostenloses WLAN', 'Sitzecke', 'Minikühlschrank', 'Regendusche', 'Schreibtisch'],
      },
      {
        id: 'lakeview-trio',
        name: 'Seeblick Trio-Zimmer',
        size: '28 m²',
        guests: '3 Gäste',
        bed: '1 King + 1 Einzelbett',
        view: 'See- & Bergpanorama',
        price: 'CHF 310 / Nacht',
        image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80',
        desc: 'Ideal für kleine Familien oder Gruppen mit großzügigem Schnitt und Panoramabalkon.',
        amenities: ['Kostenloses WLAN', 'Großer Balkon', 'Großes Bad', 'Kaffeemaschine', 'Safe'],
      },
      {
        id: 'majestic-king',
        name: 'Majestic Seeblick King Suite',
        size: '32 m²',
        guests: '2 Erwachsene',
        bed: '1 Super-King-Bett',
        view: 'Freier 180°-Seeblick',
        price: 'CHF 380 / Nacht',
        image: 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=800&q=80',
        desc: 'Erleben Sie Luxus mit riesiger Sonnenterrasse, Super-King-Bett und tiefer Badewanne.',
        amenities: ['Private Sonnenterrasse', 'Badewanne', 'Premium-Minibar', 'Luxus-Pflegeprodukte', 'Nespresso'],
      },
      {
        id: 'queens-vista',
        name: 'Queens Vista Suite',
        size: '40 m²',
        guests: '4 Gäste',
        bed: '1 King-Bett + Schlafsofa',
        view: 'Alpen & Brienzersee',
        price: 'CHF 460 / Nacht',
        image: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=800&q=80',
        desc: 'Großzügige Suite mit bodentiefen Glasfenstern, Essbereich und Hauptschlafzimmer.',
        amenities: ['Loungebereich', 'Esstisch', 'Panoramafenster', 'Doppelwaschbecken', 'Ankleidezimmer'],
      },
      {
        id: 'alpine-retreat',
        name: 'Alpine Familien-Suite',
        size: '50 m²',
        guests: '5 Gäste',
        bed: '2 King-Betten + Tagesbett',
        view: 'Zwei Balkone See & Berge',
        price: 'CHF 540 / Nacht',
        image: 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop&w=800&q=80',
        desc: 'Geräumige Suite mit 2 Schlafzimmern für unvergessliche Familienurlaube in den Schweizer Alpen.',
        amenities: ['2 Schlafzimmer', 'Zwei Balkone', 'Teeküche', 'Familienessbereich', '2 Badezimmer'],
      },
    ]
  },
  gallery: {
    title: 'Visuelle Reise durch das ORA Lake View',
    subtitle: 'Tauchen Sie ein in die Landschaft, die stilvollen Innenräume und die ruhige Atmosphäre unseres Hotels.',
    categories: {
      all: 'Alle Fotos',
      rooms: 'Zimmer & Suiten',
      view: 'Aussichten',
      dining: 'Restaurant & Bar',
      facilities: 'Ausstattung',
    }
  },
  contact: {
    title: 'Kontaktieren Sie Uns',
    subtitle: 'Wir stehen Ihnen bei Fragen, Zimmerreservierungen und Sonderwünschen gerne zur Verfügung.',
    addressTitle: 'Adresse',
    addressValue: 'Hauptstrasse 32, 3853 Niederried bei Interlaken, Schweiz',
    phoneTitle: 'Telefon',
    phoneValue: '+41 77 973 19 81',
    emailTitle: 'E-Mail',
    emailValue: 'info@oralakeview.com',
    hoursTitle: 'Rezeptionszeiten',
    hoursValue: '07:30 - 22:00 Uhr täglich',
    form: {
      name: 'Vollständiger Name',
      email: 'E-Mail-Adresse',
      subject: 'Betreff',
      message: 'Nachricht / Sonderwünsche',
      submit: 'Nachricht Senden',
      success: 'Vielen Dank! Ihre Nachricht wurde erfolgreich gesendet.',
    }
  },
  footer: {
    brandText: 'ORA Lake View Hotel & Restaurant - Ihr friedvoller Zufluchtsort in den Schweizer Alpen am Brienzersee.',
    quickLinks: 'Schnelllinks',
    roomTypes: 'Zimmertypen',
    contactUs: 'Kontakt',
    copyright: '© 2026 ORA Lake View Hotel. Alle Rechte vorbehalten.',
  },
  policies: {
    badge: 'GÄSTEINFORMATIONEN & RICHTLINIEN',
    title: 'Datenschutz & AGB',
    subtitle: 'Willkommen im ORA Lake View Hotel. Nachfolgend finden Sie unsere Datenschutzstandards, Allgemeinen Geschäftsbedingungen und Richtlinien für Ihren Aufenthalt in der Schweiz.',
    privacyTitle: 'Datenschutz-Bestimmungen',
    privacyDesc: 'ORA Lakeview verpflichtet sich zum Schutz Ihrer Privatsphäre. Wir erheben und verwenden personenbezogene Daten nur für Buchungen, Kommunikation und zur Verbesserung des Gästerlebnisses.',
    termsTitle: 'Allgemeine Geschäftsbedingungen',
    termsDesc: 'Mit der Buchung bei ORA Lakeview stimmen Sie unseren Bedingungen zu, einschließlich Check-in- und Check-out-Zeiten, Zahlungsrichtlinien und unserer Hausordnung.',
    guidelinesTitle: 'Hotelrichtlinien & Ausstattung',
    childTitle: 'Kinder-Richtlinien',
    child1: 'Kinder bis 5 Jahre übernachten kostenlos.',
    child2: 'Kinder von 6 bis 10 Jahren: CHF 50.00 pro Kind/Nacht.',
    child3: 'Kinder von 11 bis 17 Jahren: CHF 75.00 pro Kind/Nacht.',
    internetParkingTitle: 'Internet & Parken',
    internet: 'WLAN ist in allen Bereichen verfügbar und kostenlos.',
    parking: 'Kostenlose Parkplatzinformationen finden Sie in unserer Ausstattung & Services.',
    petsTitle: 'Haustiere Erlaubt',
    petsDesc: 'Haustiere sind im ORA Lake View ohne Aufpreis herzlich willkommen.',
    checkInOutTitle: 'Check-in & Check-out',
    checkIn: 'Check-in: 14:00 Uhr bis 22:00 Uhr',
    checkOut: 'Check-out: Bis 11:00 Uhr',
    requirementsTitle: 'Gästeanforderungen',
    reqAddress: 'Adresse: Gäste müssen bei der Buchung keine Adressdaten angeben.',
    reqPhone: 'Telefonnummer: Gäste müssen bei der Buchung eine Telefonnummer angeben.',
    reqAge: 'Altersgrenze / Sperrstunde: Keine Altersgrenze, keine Sperrstunde.',
    staysDamageTitle: 'Aufenthalte & Kaution',
    longStays: 'Langzeitaufenthalte: Buchungen über 30 Nächte bis max. 90 Nächte möglich.',
    groupStays: 'Gruppenbuchungen: Ausnahmeregelungen für Gruppenbuchungen ab 4 Zimmern.',
    damageDeposit: 'Kaution: Gäste müssen keine Kaution hinterlegen.',
    quote: '"Der See und die Berge sind zu meiner Landschaft, meiner echten Welt geworden."',
    author: '— GEORGES SIMENON'
  }
};
